all :
	$(MAKE) -C libpcap build install
	$(MAKE) -C libjson-c build install
	$(MAKE) -C libubox build install
	$(MAKE) -C ubus build install

clean :
	$(MAKE) -C libpcap clean
	$(MAKE) -C libjson-c clean
	$(MAKE) -C libubox clean
	$(MAKE) -C ubus clean
